/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.3. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  c$$d // clock
    , input  c$$d_0 // reset
    , input  c$$d_1 // enable

      // Outputs
    , output wire [3:0] s
    );
  // Count4r2m.hs:19:1-9
  reg [3:0] s_1 = 4'b0001;

  // register begin
  always @(posedge c$$d or  negedge  c$$d_0) begin : s_1_register
    if ( ! c$$d_0) begin
      s_1 <= 4'b0001;
    end else if (c$$d_1) begin
      s_1 <= (s_1 * 4'b0010);
    end
  end
  // register end

  assign s = s_1;


endmodule
